### ISSUE TITLE
Display issue when using totem of undying and tinted arrows from EFR

### ISSUE THREAD

**Issue by huihiuhuai** [GTNewHorizons/Backhand#11]
https://github.com/user-attachments/assets/29e11af4-ea78-4f94-8633-14ca913bf4e9

Backhand version 1.5.2

**Comment by huihiuhuai** [comment]
https://github.com/user-attachments/assets/760fbcd1-837f-4afa-aac0-f54d00764cbb

**Comment by Darek505** [comment]
<details>

<summary>If the videos do not load (broken file?):</summary>

https://github.com/user-attachments/assets/951f900c-5a04-41dc-a30d-216f7b98d399



https://github.com/user-attachments/assets/83de783d-32d8-421c-be67-8e5337f0c5be




</details>

**Comment by huihiuhuai** [comment]
video looks well for me.

**Comment by Caedis** [comment]
@Darek505 think they used 265/HEVC for encoding

**Comment by huihiuhuai** [comment]
video looks fine for me.

**Comment by huihiuhuai** [comment]
> @Darek505 think they used 265/HEVC for encoding

yes

**Comment by huihiuhuai** [comment]
https://github.com/user-attachments/assets/ed1525d2-e72f-407a-b3b0-ab4e524113a1


https://github.com/user-attachments/assets/f609b7e1-2486-4f84-b1e7-f7f530950a3a

**Comment by Caedis** [comment]
@huihiuhuai @Darek505 can both of you please try out https://github.com/GTNewHorizons/Backhand/releases/download/1.5.3-pre/backhand-1.5.3-pre.jar to see if any issues still persist?

**Comment by Darek505** [comment]
<details>

<summary>I can confirm that the problem with totem is still relevant, the problem with arrows seems to have been resolved</summary>

https://github.com/user-attachments/assets/5a7ae3c1-3c3d-4ec8-9592-6c80d76d04ad

https://github.com/user-attachments/assets/cdf03be6-ddf3-4692-9664-bd4b9459e6b8



</details>

**Comment by huihiuhuai** [comment]
Version 1.5.7-pre. Totem issue is fixed. Tinted arrow issue persists.

**Comment by huihiuhuai** [comment]
tinted arrows issue persists 

> 2024-07-25.15-59-56.00_00_02-00_00_12.mp4

**Comment by Lyfts** [comment]
Can you give https://github.com/GTNewHorizons/Backhand/releases/tag/1.5.9-pre a try, I'm 99% sure it's fixed for good now

**Comment by Darek505** [comment]
(1.5.9-pre) I can confirm that it is fixed

**Comment by huihiuhuai** [comment]
perfectly fixed
