### ISSUE TITLE
Some items do not update quantity after use (visual only) 1.5.3-pre

### ISSUE THREAD

**Issue by Darek505** [GTNewHorizons/Backhand#15]
for example, using fireworks or end crystals in the offhand does not update their visual quantity, but if you take them into your main hand and right-click on the air, their number will be updated

https://github.com/user-attachments/assets/83f67133-377d-48a1-90d8-e8a345e17940

<details>

<summary>probably related problem with hbm's ntm</summary>

https://github.com/user-attachments/assets/890fa1db-0253-4b5b-b583-1a10a9c48276

(this video shows that the number of bullets in the pistol does not change after reloading, but if you right-click in the air, the counter will be updated (it doesn’t have to be a second pistol in offhand, it can be absolutely any item))

</details>

**Comment by Lyfts** [comment]
That's with `"Use inventory slot"` turned on right?

**Comment by Darek505** [comment]
> That's with `"Use inventory slot"` turned on right?

Now I tested with "Use inventory slot"=false, the problem is still there, so the problem exists in both cases

**Comment by Darek505** [comment]
(1.5.9-pre) The problem with fireworks / end crystals, etc. has been resolved.
There is still problem with the number of bullets with hbm's ntm. Is it possible that when an item is in the offhand, it blocks the item in the main hand from updating?

(although perhaps this is basically a problem with items that are updated after pressing a key)
