### ISSUE TITLE
Visual glitch when clearing inventory (1.5.3-pre)

### ISSUE THREAD

**Issue by huihiuhuai** [GTNewHorizons/Backhand#16]
https://github.com/user-attachments/assets/2cd638b0-442f-4284-9b39-b3cc1dbdff4b

Backhand version is 1.5.3-pre.

**Comment by Darek505** [comment]
(1.5.9-pre) problem is present with `B:"Use inventory slot"=false`, and only the item in the offhand and the one in the hand are not cleared, the rest of the hotbar is cleared

<details>

<summary></summary>

https://github.com/user-attachments/assets/63c31cb6-3c80-4c3c-a10f-00af38f6076d

</details>
