### ISSUE TITLE
Slot switching breaks

### ISSUE THREAD

**Issue by GedeonGrays** [GTNewHorizons/Backhand#2]
Hello o/

**Backhand version:** 1.5.0
There are no other mods.

When I take any item in my second hand, the slot switching breaks. It is almost impossible to use both main and second hand normally.
Problem demonstration:

https://github.com/user-attachments/assets/6e825bb4-58c2-4045-9f55-cafbef7dc20d

**Comment by Caedis** [comment]
Looks to be intended behavior
```
	# If enabled, a hotswap will be performed every tick if the main hand has no use or is empty.
    # This hotswap allows for many more items like fishing rods to be used in the offhand, but may be unstable.
    B:"Offhand Tick Hotswap"=true
```

**Comment by GedeonGrays** [comment]
Yes, disabling this parameter did indeed solve the problem. Really didn't realize it could be so unstable ¯\_(ツ)_/¯

But now I get a crash when trying to place the torch from the second hand: [crash-2024-07-23_08.22.10-client.txt](https://github.com/user-attachments/files/16344095/crash-2024-07-23_08.22.10-client.txt)

**Comment by huihiuhuai** [comment]
> Yes, disabling this parameter did indeed solve the problem. Really didn't realize it could be so unstable ¯_(ツ)_/¯
> 
> But now I get a crash when trying to place the torch from the second hand: [crash-2024-07-23_08.22.10-client.txt](https://github.com/user-attachments/files/16344095/crash-2024-07-23_08.22.10-client.txt)

+1

**Comment by Caedis** [comment]
Already fixed, try the latest version.
