### ISSUE TITLE
Crash when switching the patterns of carpenter's bed with offhand

### ISSUE THREAD

**Issue by huihiuhuai** [GTNewHorizons/Backhand#22]
https://pastebin.com/pBJxtW2C

**Comment by Lyfts** [comment]
I can't reproduce. Can you check if it still happens with https://github.com/GTNewHorizons/Backhand/releases/tag/1.5.7-pre?

**Comment by huihiuhuai** [comment]
I also happens with 1.5.7.

**Comment by Lyfts** [comment]
Which block are you using it on and can you send a new log?

**Comment by huihiuhuai** [comment]
ohhh i was using hammer right click on carpenters bed to switch colors

**Comment by huihiuhuai** [comment]
cant reproduce in 1.5.8-pre

**Comment by huihiuhuai** [comment]
https://github.com/user-attachments/assets/b060e372-826c-4115-80e9-454b437c1093

Crash with Carpenter's garage door.
https://pastebin.com/QLuAZK1K

**Comment by Lyfts** [comment]
That is hopefully be fixed in https://github.com/GTNewHorizons/Backhand/releases/tag/1.5.10-pre

**Comment by huihiuhuai** [comment]
[crash-2024-08-05_13.28.44-client.txt](https://github.com/user-attachments/files/16491106/crash-2024-08-05_13.28.44-client.txt)
1.5.10-pre

**Comment by Lyfts** [comment]
Third times the charm https://github.com/GTNewHorizons/Backhand/releases/tag/1.5.11-pre this time it should definitely be fixed. 
You'll need to install https://github.com/GTNewHorizons/GTNHLib/releases if you don't already have it.
