### ISSUE TITLE
Cannot use Chest Transporter to pick up chests when offhand is holding an item 

### ISSUE THREAD

**Issue by huihiuhuai** [GTNewHorizons/Backhand#24]

**Comment by huihiuhuai** [comment]
Chest Transporter

**Comment by Lyfts** [comment]
Are you using it on a vanilla chest or some modded chest?

**Comment by huihiuhuai** [comment]
Vanilla chest. There was torch or enchanted book in the offhand.

**Comment by Lyfts** [comment]
![bh_chest_transporter](https://github.com/user-attachments/assets/9fd0bc91-606e-4c14-9ec9-92d44a71863c)
It seems to be fixed by one of the later commits, I'll' make a new pre version some time tomorrow.

**Comment by Lyfts** [comment]
Try with https://github.com/GTNewHorizons/Backhand/releases/tag/1.5.8-pre

**Comment by Darek505** [comment]
(1.5.9-pre) I can confirm that the chest can be taken, but it is no possible to place it when there is another item in the offhand:

<details>

<summary></summary>

https://github.com/user-attachments/assets/10b68707-c2b3-4d05-89e1-9e0ca9c07446


</details>

**Comment by Lyfts** [comment]
Yep the chest transporter uses an event to place the chest rather than `onItemUse` or `onItemUseFirst,` which means that we would have to implement explicit support for that.
