### ISSUE TITLE
logspam from backhand

### ISSUE THREAD

**Issue by brandyyn** [GTNewHorizons/Backhand#42]
### Mod Version

backhand-1.5.14

### Bug Report

![image](https://github.com/user-attachments/assets/04e8dc3a-54cb-4b06-8ce1-9695a435d1aa)

### Java Version

Java 8

### Mod List or GTNH Pack Version

backhand-1.5.14

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.

**Comment by Caedis** [comment]
Update betterquesting
https://github.com/GTNewHorizons/BetterQuesting/pull/149

**Comment by brandyyn** [comment]
> Update betterquesting [GTNewHorizons/BetterQuesting#149](https://github.com/GTNewHorizons/BetterQuesting/pull/149)

i'm using betterquesting 3.6.20, this commit was added in 3.6.16 but i will try .22
