### ISSUE TITLE
Bow is reset if you look at the mob (if "Use inventory slot"=false)

### ISSUE THREAD

**Issue by Darek505** [GTNewHorizons/Backhand#5]
###     `B:"Use inventory slot"=true` (no error)
https://github.com/user-attachments/assets/6d93e7c0-db65-418c-92fb-e1010c822cf8

---

###     `B:"Use inventory slot"=false`
https://github.com/user-attachments/assets/7315be84-dbdf-4c98-837c-e77fe2663f26

**Comment by huihiuhuai** [comment]
https://github.com/user-attachments/assets/feef88e5-bbd6-4b1c-b38c-af6fc3eb5a6d

issue persists in 1.5.2
