### ISSUE TITLE
Incorrect use of fireworks when flying with efr elytra

### ISSUE THREAD

**Issue by Darek505** [GTNewHorizons/Backhand#7]
https://github.com/user-attachments/assets/f1a015bb-f83e-4b47-aa04-5a13b3c925d1

The video shows that after using fireworks in the offhand, fireworks appear in the main hand (you can see that before use there were 5 of them in the offhand, after use (in the offhand) there were 4 of them, but 5 appeared in the main hand) fireworks that appeared in the main hand prevented the use of fireworks from the offhand, that is, when you press the right mouse button, they are not activated. Next you can see that after using fireworks from the main hand on the ground, they disappeared

**Comment by huihiuhuai** [comment]
issue persists in 1.5.2

**Comment by huihiuhuai** [comment]
https://github.com/user-attachments/assets/091febd2-75e6-411c-9794-e0e3576710d1

issue persists in 1.5.2
