### ISSUE TITLE
Offhand item disappears when switching dimensions

### ISSUE THREAD

**Issue by huihiuhuai** [GTNewHorizons/Backhand#8]
https://github.com/user-attachments/assets/c6ba0ae9-c094-4f69-bef7-87fc24e87c06

Steps to reproduce:
1. Start a new Minecraft world with Backhand 1.5.1.
2. Put an item in the offhand slot.
3. Travel to a different dimension.
4. Observe the offhand item is no longer visible until you press the offhand key.

Expected behavior:
Offhand item should remain visible when switching dimensions without requiring any additional input.

**Comment by huihiuhuai** [comment]
https://github.com/user-attachments/assets/c971bcb0-fce1-4765-9513-58cb4958e5ea

issue persists in 1.5.2

**Comment by Lyfts** [comment]
Aight can you send your full mod list because I couldn't reproduce it when I tested it yesterday

**Comment by huihiuhuai** [comment]
EFR 2.6.0
Backhand 1.5.2
Bauble EX 2.1.4

**Comment by huihiuhuai** [comment]
EFR 2.6.0
Backhand 1.5.2
Baubles EX 2.1.4

**Comment by huihiuhuai** [comment]
also tested with only Backhand installed

**Comment by Lyfts** [comment]
![bh_portal2](https://github.com/user-attachments/assets/92c7801f-4c20-4563-9ec3-49ca1e632b24)
I still can't reproduce. Have you changed any specific config options?

**Comment by huihiuhuai** [comment]
i set `Use inventory slot` to true now thr offhand item doesn't dissapear

**Comment by Lyfts** [comment]
The video I sent above has that option disabled (the default) but it also works fine with it enabled.

Can you try on a new world with that option disabled? It uses a `IExtendedEntityProperties` so it's possible that something has gone wrong there.

**Comment by huihiuhuai** [comment]
The offhand item still disappears.

**Comment by huihiuhuai** [comment]
sloved in 1.5.3 version
